version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:15.10
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Lint JS
          command: npm run lint:js
      - run:
          name: Lint SCSS
          command: npm run lint:scss
      - run:
          name: Build
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - 'dist'
  deploy:
    docker:
      - image: cimg/node:15.10
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Deploy
          command: echo "deploy"

workflows:
  build-and-delpoy:
    jobs:
      - build
      - deploy:
          context: earthquake-zen-garden
          requires:
            - build
          filters:
            branches:
              only:
                - main
